### ISSUE TITLE
Convert <br> to '\n' in `text`?

### ISSUE THREAD

**Issue by failable** [causal-agent/scraper#178]
The following code snippet outputs `"Hello, world!good bye"`.
```
    use scraper::{Html, Selector};

    let fragment = Html::parse_fragment("<div>Hello, world!<br><p>good bye</p></div>");
    let selector = Selector::parse("div").unwrap();

    let div = fragment.select(&selector).next().unwrap();

    println!("{:#?}", div.text().collect::<String>());
```
Would it better to output `"Hello, world!\ngood bye"`?

**Comment by adamreichold** [comment]
If you want this particular transformation, you will need to replace the `<br/>` [`Element`](https://docs.rs/scraper/latest/scraper/node/enum.Node.html#variant.Element) node by a `\n` [`Text`](https://docs.rs/scraper/latest/scraper/node/enum.Node.html#variant.Text) node and then use `.text().collect::<String>()`.

Alternatively, you can use [`.descendants()`](https://docs.rs/ego-tree/latest/ego_tree/struct.NodeRef.html#method.descendants) instead of `.text()` and filter for text nodes and `<br/>` tags directly.
