### ISSUE TITLE
how return iterator from function

### ISSUE THREAD

**Issue by D1mon** [causal-agent/scraper#43]
```rust
async fn get_links() -> impl std::iter::Iterator {
    let res = reqwest::get("http://site").await.unwrap();
    let doc = Html::parse_document(&res.text().await.unwrap());
    let sel: Selector = Selector::parse("a").expect("can't parse selector");
    doc.select(&sel)
                ---- `sel` is borrowed here
    --- `doc` is borrowed here
}
```

maybe I'm doing something wrong or need to be added to the library to fix the problem?

**Comment by talzion12** [comment]
The problem is that the iterator you're returning is borrowing `sel` which is a local variable.
You could use `lazy_static` to store `sel` globally like so:

```rust
lazy_static::lazy_static! {
  static ref LINK_SELECTOR: Selector = Selector::parse("a").expect("can't parse selector");
}
```
This way you wouldn't parse the selector each time you call `get_links`.

I think another option to solve this would be to create another `Iterator` implementation that owns the selector. I believe this is the original implementation: https://github.com/causal-agent/scraper/blob/master/src/element_ref/mod.rs#L89
